apiVersion: v1
kind: ConfigMap
metadata:
  name: yelp-config
  namespace: yelp
data:
  DATABASE_NAME: "yelp_db"
  MONGO_URL: "mongodb://mongodb-service:27017"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
