from app.database import SessionLocal
from app.models import Restaurant


INDIAN_DISH_KEYWORDS = [
    "butter chicken",
    "chicken tikka masala",
    "tandoori chicken",
    "chicken tikka",
    "biryani",
    "veg biryani",
    "chicken biryani",
    "mutton biryani",
    "paneer biryani",
    "rogan josh",
    "vindaloo",
    "korma",
    "chicken korma",
    "lamb curry",
    "goat curry",
    "mutton curry",
    "nihari",
    "chettinad chicken",
    "dal makhani",
    "dal fry",
    "dal tadka",
    "chana masala",
    "chole",
    "rajma",
    "palak paneer",
    "paneer butter masala",
    "shahi paneer",
    "paneer tikka",
    "paneer curry",
    "malai kofta",
    "baingan bharta",
    "aloo gobi",
    "bhindi masala",
    "kadhi",
    "sambar",
    "rasam",
    "fish curry",
    "egg curry",
    "naan",
    "butter naan",
    "garlic naan",
    "tandoori roti",
    "roti",
    "paratha",
    "aloo paratha",
    "kulcha",
    "pulao",
    "jeera rice",
    "ghee rice",
    "khichdi",
    "dosa",
    "masala dosa",
    "rava dosa",
    "idli",
    "vada",
    "medu vada",
    "uttapam",
    "upma",
    "poori",
    "puri",
    "appam",
    "samosa",
    "papdi chaat",
    "pani puri",
    "golgappa",
    "bhel puri",
    "sev puri",
    "chaat",
    "pakora",
    "onion bhaji",
    "pav bhaji",
    "kachori",
    "cutlet",
    "chicken 65",
    "gobi manchurian",
    "seekh kebab",
    "chicken kebab",
    "kebab",
    "tandoori platter",
    "hariyali chicken",
    "malai tikka",
    "gulab jamun",
    "jalebi",
    "kheer",
    "rasmalai",
    "kulfi",
    "lassi",
    "mango lassi",
    "masala chai",
    "chai",
    "indian food",
    "curry",
    "spicy",
    "vegetarian",
    "halal",
    "tandoor",
    "🍛",
    "🍗",
    "🥘",
]

ITALIAN_DISH_KEYWORDS = [
    "pasta",
    "spaghetti",
    "fettuccine",
    "alfredo",
    "lasagna",
    "ravioli",
    "gnocchi",
    "risotto",
    "penne",
    "carbonara",
    "margherita pizza",
    "pizza",
    "tiramisu",
    "bruschetta",
    "garlic bread",
    "minestrone",
    "italian",
    "wine",
    "date night",
    "romantic",
    "🍝",
    "🍕",
]

CHINESE_DISH_KEYWORDS = [
    "fried rice",
    "noodles",
    "chow mein",
    "lo mein",
    "kung pao chicken",
    "orange chicken",
    "sweet and sour chicken",
    "dumplings",
    "wontons",
    "spring rolls",
    "hot and sour soup",
    "mapo tofu",
    "general tso chicken",
    "szechuan",
    "chinese food",
    "🥡",
    "🥢",
]

JAPANESE_DISH_KEYWORDS = [
    "sushi",
    "sashimi",
    "ramen",
    "udon",
    "tempura",
    "teriyaki",
    "miso soup",
    "bento",
    "yakitori",
    "nigiri",
    "japanese food",
    "🍣",
    "🍜",
]

THAI_DISH_KEYWORDS = [
    "pad thai",
    "green curry",
    "red curry",
    "tom yum",
    "tom kha",
    "thai iced tea",
    "drunken noodles",
    "massaman curry",
    "satay",
    "thai food",
    "🍜",
    "🌶️",
]

COFFEE_KEYWORDS = [
    "coffee",
    "black coffee",
    "espresso",
    "latte",
    "cappuccino",
    "americano",
    "cold brew",
    "pour over",
    "matcha",
    "chai latte",
    "cafe",
    "coffee shop",
    "pastries",
    "croissant",
    "☕",
    "🥐",
]

BREAKFAST_KEYWORDS = [
    "omelette",
    "omelet",
    "pancakes",
    "waffles",
    "french toast",
    "eggs",
    "breakfast burrito",
    "avocado toast",
    "brunch",
    "breakfast",
    "🍳",
    "🥞",
]

JUICE_KEYWORDS = [
    "juice",
    "fresh juice",
    "smoothie",
    "smoothie bowl",
    "fruit bowl",
    "acai bowl",
    "protein shake",
    "green juice",
    "orange juice",
    "mango smoothie",
    "strawberry smoothie",
    "healthy drinks",
    "🥤",
    "🍓",
    "🍌",
    "🥭",
]

DESSERT_KEYWORDS = [
    "dessert",
    "cake",
    "cheesecake",
    "brownie",
    "ice cream",
    "gelato",
    "cookies",
    "cupcake",
    "pastry",
    "bakery",
    "tiramisu",
    "🧁",
    "🍰",
    "🍨",
]

SEAFOOD_KEYWORDS = [
    "seafood",
    "grilled salmon",
    "shrimp",
    "lobster",
    "fish tacos",
    "clam chowder",
    "oysters",
    "crab cakes",
    "sushi",
    "grilled fish",
    "🦐",
    "🐟",
]

PIZZA_KEYWORDS = [
    "pizza",
    "pepperoni pizza",
    "margherita pizza",
    "cheese pizza",
    "veggie pizza",
    "garlic knots",
    "calzone",
    "slice",
    "🍕",
]

BURGER_KEYWORDS = [
    "burger",
    "cheeseburger",
    "double burger",
    "fries",
    "chicken sandwich",
    "milkshake",
    "onion rings",
    "cheap eats",
    "🍔",
    "🍟",
]

SEED_RESTAURANTS = [
    {
        "name": "Morning Bloom Cafe",
        "cuisine_type": "Coffee & Tea",
        "address": "101 Central Ave",
        "city": "Phoenix",
        "state": "AZ",
        "zip_code": "85001",
        "contact_phone": "602-111-1001",
        "contact_email": "hello@morningbloom.com",
        "description": "Cozy cafe serving black coffee, espresso, cappuccino, latte, croissants, avocado toast, pastries, and light breakfast plates.",
        "hours_text": "Mon-Sun 7:00 AM - 5:00 PM",
        "photos": [],
        "keywords": COFFEE_KEYWORDS + BREAKFAST_KEYWORDS,
        "price_range": "$",
        "amenities": ["wifi", "casual", "quiet", "takeout"],
        "is_open": True,
    },
    {
        "name": "Sunny Side Brunch House",
        "cuisine_type": "Breakfast & Brunch",
        "address": "220 Maple St",
        "city": "Tempe",
        "state": "AZ",
        "zip_code": "85281",
        "contact_phone": "480-111-1002",
        "contact_email": "info@sunnysidebrunch.com",
        "description": "Popular brunch place known for omelette plates, pancakes, waffles, French toast, breakfast burritos, and fresh coffee.",
        "hours_text": "Daily 6:30 AM - 2:30 PM",
        "photos": [],
        "keywords": BREAKFAST_KEYWORDS + COFFEE_KEYWORDS,
        "price_range": "$$",
        "amenities": ["family friendly", "casual", "outdoor seating"],
        "is_open": True,
    },
    {
        "name": "Tandoori Flame Kitchen",
        "cuisine_type": "Indian",
        "address": "55 Desert Road",
        "city": "Phoenix",
        "state": "AZ",
        "zip_code": "85004",
        "contact_phone": "602-111-1003",
        "contact_email": "team@tandooriflame.com",
        "description": "Authentic Indian restaurant serving tandoori chicken, butter chicken, chicken tikka masala, biryani, naan, dal makhani, paneer dishes, kebabs, samosas, and chai in a casual family-friendly setting.",
        "hours_text": "Daily 11:00 AM - 10:00 PM",
        "photos": [],
        "keywords": INDIAN_DISH_KEYWORDS + ["casual indian dining", "family dinner", "takeout"],
        "price_range": "$$",
        "amenities": ["family friendly", "takeout", "dinner"],
        "is_open": True,
    },
    {
        "name": "Royal Spice Palace",
        "cuisine_type": "Indian",
        "address": "77 Camelback Rd",
        "city": "Scottsdale",
        "state": "AZ",
        "zip_code": "85251",
        "contact_phone": "480-111-1004",
        "contact_email": "contact@royalspice.com",
        "description": "Upscale Indian dining with romantic ambiance, candlelit dinner service, rich curries, paneer specialties, biryani, naan, kebabs, and elegant desserts for date nights and anniversaries.",
        "hours_text": "Daily 5:00 PM - 10:30 PM",
        "photos": [],
        "keywords": INDIAN_DISH_KEYWORDS + [
            "romantic",
            "anniversary",
            "date night",
            "upscale indian dining",
            "fine dining",
            "special occasion",
            "quiet",
            "✨",
            "❤️",
        ],
        "price_range": "$$$",
        "amenities": ["romantic", "upscale", "quiet", "dinner"],
        "is_open": True,
    },
    {
        "name": "Bella Notte",
        "cuisine_type": "Italian",
        "address": "140 Grand Ave",
        "city": "Phoenix",
        "state": "AZ",
        "zip_code": "85003",
        "contact_phone": "602-111-1005",
        "contact_email": "host@bellanotte.com",
        "description": "Romantic Italian restaurant with candlelit seating, handmade pasta, lasagna, ravioli, tiramisu, and a date-night atmosphere.",
        "hours_text": "Tue-Sun 5:00 PM - 11:00 PM",
        "photos": [],
        "keywords": ITALIAN_DISH_KEYWORDS + ["anniversary", "candlelight", "fine dining", "❤️"],
        "price_range": "$$$",
        "amenities": ["romantic", "quiet", "fine dining", "dinner"],
        "is_open": True,
    },
    {
        "name": "Budget Bites Grill",
        "cuisine_type": "American",
        "address": "330 Union St",
        "city": "Mesa",
        "state": "AZ",
        "zip_code": "85201",
        "contact_phone": "480-111-1006",
        "contact_email": "hi@budgetbites.com",
        "description": "Affordable burgers, fries, chicken sandwiches, onion rings, and late-night comfort food for students and families.",
        "hours_text": "Daily 10:00 AM - 11:00 PM",
        "photos": [],
        "keywords": BURGER_KEYWORDS,
        "price_range": "$",
        "amenities": ["casual", "family friendly", "takeout"],
        "is_open": True,
    },
    {
        "name": "Green Root Vegan Kitchen",
        "cuisine_type": "Vegan",
        "address": "88 University Dr",
        "city": "Tempe",
        "state": "AZ",
        "zip_code": "85281",
        "contact_phone": "480-111-1007",
        "contact_email": "plants@greenroot.com",
        "description": "Plant-based kitchen with vegan bowls, tofu wraps, salads, smoothies, dairy-free desserts, and healthy lunches.",
        "hours_text": "Daily 10:00 AM - 9:00 PM",
        "photos": [],
        "keywords": ["vegan", "plant based", "vegetarian", "healthy", "tofu", "salad", "dairy free", "smoothie", "🥗", "🌱"],
        "price_range": "$$",
        "amenities": ["casual", "healthy", "takeout"],
        "is_open": True,
    },
    {
        "name": "Moonlight Rooftop Dining",
        "cuisine_type": "Mediterranean",
        "address": "12 Skyline Blvd",
        "city": "Scottsdale",
        "state": "AZ",
        "zip_code": "85258",
        "contact_phone": "480-111-1008",
        "contact_email": "book@moonlightrooftop.com",
        "description": "Romantic rooftop Mediterranean dining with city views, date-night ambiance, grilled seafood, and soft lighting.",
        "hours_text": "Wed-Sun 5:00 PM - 11:30 PM",
        "photos": [],
        "keywords": ["romantic", "anniversary", "date", "rooftop", "mediterranean", "seafood", "special occasion", "🌙", "🍷"] + SEAFOOD_KEYWORDS,
        "price_range": "$$$",
        "amenities": ["romantic", "outdoor seating", "upscale", "quiet"],
        "is_open": True,
    },
    {
        "name": "Phoenix Pancake Corner",
        "cuisine_type": "Breakfast & Brunch",
        "address": "900 Pine St",
        "city": "Phoenix",
        "state": "AZ",
        "zip_code": "85006",
        "contact_phone": "602-111-1009",
        "contact_email": "hello@pancakecorner.com",
        "description": "Neighborhood breakfast stop with pancakes, omelettes, waffles, breakfast burritos, and endless coffee refills.",
        "hours_text": "Daily 6:00 AM - 3:00 PM",
        "photos": [],
        "keywords": BREAKFAST_KEYWORDS + COFFEE_KEYWORDS,
        "price_range": "$",
        "amenities": ["casual", "family friendly", "breakfast"],
        "is_open": True,
    },
    {
        "name": "Desert Brew House",
        "cuisine_type": "Coffee & Tea",
        "address": "451 Market St",
        "city": "Scottsdale",
        "state": "AZ",
        "zip_code": "85260",
        "contact_phone": "480-111-1010",
        "contact_email": "brew@desertbrew.com",
        "description": "Modern coffee house offering espresso drinks, pour-over coffee, cold brew, matcha, bakery items, and study-friendly seating.",
        "hours_text": "Mon-Sun 7:00 AM - 6:00 PM",
        "photos": [],
        "keywords": COFFEE_KEYWORDS + DESSERT_KEYWORDS,
        "price_range": "$$",
        "amenities": ["wifi", "casual", "quiet"],
        "is_open": True,
    },
    {
        "name": "Taco Fiesta Street Kitchen",
        "cuisine_type": "Mexican",
        "address": "780 Fiesta Ln",
        "city": "Mesa",
        "state": "AZ",
        "zip_code": "85202",
        "contact_phone": "480-111-1011",
        "contact_email": "hola@tacofiesta.com",
        "description": "Fun Mexican street-food spot with tacos, quesadillas, burritos, churros, and quick affordable meals.",
        "hours_text": "Daily 11:00 AM - 10:00 PM",
        "photos": [],
        "keywords": ["tacos", "burrito", "quesadilla", "cheap eats", "mexican", "street food", "🌮", "🌯"],
        "price_range": "$",
        "amenities": ["casual", "family friendly", "takeout"],
        "is_open": True,
    },
    {
        "name": "Cozy Corner Bakery Cafe",
        "cuisine_type": "Bakery",
        "address": "18 Maple Ave",
        "city": "Tempe",
        "state": "AZ",
        "zip_code": "85282",
        "contact_phone": "480-111-1012",
        "contact_email": "fresh@cozycorner.com",
        "description": "Small bakery cafe with muffins, cakes, sandwiches, coffee, tea, cookies, and a quiet study-friendly vibe.",
        "hours_text": "Mon-Sat 7:00 AM - 4:00 PM",
        "photos": [],
        "keywords": DESSERT_KEYWORDS + COFFEE_KEYWORDS,
        "price_range": "$",
        "amenities": ["quiet", "wifi", "casual"],
        "is_open": True,
    },
    {
        "name": "Fresh Squeeze Juice Bar",
        "cuisine_type": "Juice & Smoothies",
        "address": "602 Health Ave",
        "city": "Phoenix",
        "state": "AZ",
        "zip_code": "85008",
        "contact_phone": "602-111-1013",
        "contact_email": "sip@freshsqueeze.com",
        "description": "Healthy juice and smoothie bar serving fruit bowls, acai bowls, green juice, mango smoothies, protein shakes, and fresh snacks.",
        "hours_text": "Daily 8:00 AM - 7:00 PM",
        "photos": [],
        "keywords": JUICE_KEYWORDS,
        "price_range": "$$",
        "amenities": ["healthy", "casual", "takeout"],
        "is_open": True,
    },
    {
        "name": "Roma Pasta Kitchen",
        "cuisine_type": "Italian",
        "address": "415 Olive St",
        "city": "Tempe",
        "state": "AZ",
        "zip_code": "85283",
        "contact_phone": "480-111-1014",
        "contact_email": "ciao@romapasta.com",
        "description": "Casual Italian kitchen with spaghetti, fettuccine alfredo, ravioli, garlic bread, pizza, and tiramisu.",
        "hours_text": "Daily 11:00 AM - 10:00 PM",
        "photos": [],
        "keywords": ITALIAN_DISH_KEYWORDS + ["casual dinner", "family pasta night"],
        "price_range": "$$",
        "amenities": ["casual", "family friendly", "takeout"],
        "is_open": True,
    },
    {
        "name": "Golden Wok Express",
        "cuisine_type": "Chinese",
        "address": "700 Lantern Rd",
        "city": "Phoenix",
        "state": "AZ",
        "zip_code": "85009",
        "contact_phone": "602-111-1015",
        "contact_email": "wok@goldenwok.com",
        "description": "Chinese kitchen serving fried rice, noodles, dumplings, orange chicken, chow mein, wontons, and quick lunch specials.",
        "hours_text": "Daily 11:00 AM - 9:30 PM",
        "photos": [],
        "keywords": CHINESE_DISH_KEYWORDS,
        "price_range": "$$",
        "amenities": ["casual", "takeout", "lunch"],
        "is_open": True,
    },
    {
        "name": "Sakura Harbor",
        "cuisine_type": "Japanese",
        "address": "233 Blossom Way",
        "city": "Scottsdale",
        "state": "AZ",
        "zip_code": "85254",
        "contact_phone": "480-111-1016",
        "contact_email": "hello@sakuraharbor.com",
        "description": "Japanese restaurant with sushi rolls, ramen bowls, tempura, teriyaki, sashimi, and cozy evening dining.",
        "hours_text": "Daily 12:00 PM - 10:00 PM",
        "photos": [],
        "keywords": JAPANESE_DISH_KEYWORDS,
        "price_range": "$$",
        "amenities": ["casual", "quiet", "dinner"],
        "is_open": True,
    },
    {
        "name": "Bangkok Spice Table",
        "cuisine_type": "Thai",
        "address": "612 Orchid St",
        "city": "Mesa",
        "state": "AZ",
        "zip_code": "85203",
        "contact_phone": "480-111-1017",
        "contact_email": "thai@bangkokspice.com",
        "description": "Flavorful Thai spot serving pad thai, green curry, tom yum, drunken noodles, satay, and Thai iced tea.",
        "hours_text": "Daily 11:00 AM - 10:00 PM",
        "photos": [],
        "keywords": THAI_DISH_KEYWORDS,
        "price_range": "$$",
        "amenities": ["casual", "takeout", "spicy food"],
        "is_open": True,
    },
    {
        "name": "Harbor Catch Seafood Grill",
        "cuisine_type": "Seafood",
        "address": "89 Bay View Dr",
        "city": "Phoenix",
        "state": "AZ",
        "zip_code": "85010",
        "contact_phone": "602-111-1018",
        "contact_email": "catch@harborgrill.com",
        "description": "Seafood grill featuring grilled salmon, shrimp platters, oysters, crab cakes, fish tacos, and date-night dinner specials.",
        "hours_text": "Tue-Sun 4:00 PM - 10:30 PM",
        "photos": [],
        "keywords": SEAFOOD_KEYWORDS + ["date night", "special dinner", "romantic seafood"],
        "price_range": "$$$",
        "amenities": ["romantic", "quiet", "dinner"],
        "is_open": True,
    },
    {
        "name": "Stone Oven Pizza Co",
        "cuisine_type": "Pizza",
        "address": "910 Brick Lane",
        "city": "Tempe",
        "state": "AZ",
        "zip_code": "85284",
        "contact_phone": "480-111-1019",
        "contact_email": "pizza@stoneoven.com",
        "description": "Neighborhood pizza place serving margherita pizza, pepperoni pizza, veggie pizza, calzones, garlic knots, and slices.",
        "hours_text": "Daily 11:00 AM - 11:00 PM",
        "photos": [],
        "keywords": PIZZA_KEYWORDS,
        "price_range": "$$",
        "amenities": ["casual", "family friendly", "takeout"],
        "is_open": True,
    },
    {
        "name": "Sweet Tooth Dessert Lounge",
        "cuisine_type": "Desserts",
        "address": "305 Cherry St",
        "city": "Scottsdale",
        "state": "AZ",
        "zip_code": "85255",
        "contact_phone": "480-111-1020",
        "contact_email": "treats@sweettooth.com",
        "description": "Dessert lounge with cheesecake, brownies, cupcakes, ice cream, gelato, cookies, coffee, and late-night sweets.",
        "hours_text": "Daily 1:00 PM - 11:30 PM",
        "photos": [],
        "keywords": DESSERT_KEYWORDS + COFFEE_KEYWORDS,
        "price_range": "$$",
        "amenities": ["casual", "date night", "dessert stop"],
        "is_open": True,
    },
]


def seed_restaurants():
    db = SessionLocal()

    try:
        for item in SEED_RESTAURANTS:
            existing = db.query(Restaurant).filter(Restaurant.name == item["name"]).first()

            if existing:
                for key, value in item.items():
                    setattr(existing, key, value)
            else:
                restaurant = Restaurant(**item)
                db.add(restaurant)

        db.commit()
        print(f"Seeded {len(SEED_RESTAURANTS)} restaurants successfully.")

    except Exception as e:
        db.rollback()
        print("Seeding failed:", str(e))

    finally:
        db.close()


if __name__ == "__main__":
    seed_restaurants()