apiVersion: apps/v1
kind: Deployment
metadata:
  name: owner-service
  namespace: yelp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: owner-service
  template:
    metadata:
      labels:
        app: owner-service
    spec:
      containers:
        - name: owner-service
          image: yelp-owner-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8002
          envFrom:
            - configMapRef:
                name: yelp-config
            - secretRef:
                name: yelp-secrets
          volumeMounts:
            - name: uploads-storage
              mountPath: /app/uploads
          readinessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 20
            periodSeconds: 10
      volumes:
        - name: uploads-storage
          persistentVolumeClaim:
            claimName: uploads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: owner-service
  namespace: yelp
spec:
  selector:
    app: owner-service
  ports:
    - port: 8002
      targetPort: 8002
  type: ClusterIP
