apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: yelp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: 896241235820.dkr.ecr.us-east-1.amazonaws.com/yelp-user-service:aws-v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          envFrom:
            - configMapRef:
                name: yelp-config
            - secretRef:
                name: yelp-secrets
          volumeMounts:
            - name: uploads-storage
              mountPath: /app/uploads
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 20
            periodSeconds: 10
      volumes:
        - name: uploads-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: yelp
spec:
  selector:
    app: user-service
  ports:
    - port: 8001
      targetPort: 8001
  type: ClusterIP